name: terraform-ci

on:
  push:
    branches: [ "main" ]
  pull_request:

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-northeast-1
  TF_VERSION: 1.5.7
  TF_IN_AUTOMATION: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::529928146765:role/fridgeops-ci-tf-plan
          aws-region: ${{ env.AWS_REGION }}

      # --- infra/ci ---
      - name: Terraform fmt (infra/ci)
        working-directory: infra/ci
        run: terraform fmt -check

      - name: Terraform init (infra/ci)
        working-directory: infra/ci
        run: terraform init

      - name: Terraform validate (infra/ci)
        working-directory: infra/ci
        run: terraform validate

      - name: Terraform plan (infra/ci)
        working-directory: infra/ci
        run: terraform plan

      # --- infra/main ---
      - name: Terraform fmt (infra/main)
        working-directory: infra/main
        run: terraform fmt -check

      - name: Terraform init (infra/main)
        working-directory: infra/main
        run: terraform init

      - name: Terraform validate (infra/main)
        working-directory: infra/main
        run: terraform validate

      - name: Terraform plan (infra/main)
        working-directory: infra/main
        run: terraform plan
